create table if not exists public.ranking (
  id bigint generated by default as identity primary key,
  nome varchar(100) not null,
  pontuacao integer not null check (pontuacao >= 0 and pontuacao <= 999999),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.ranking enable row level security;

grant usage on schema public to anon;
grant select, insert on public.ranking to anon;

revoke update on public.ranking from anon;
revoke delete on public.ranking from anon;

create policy "ranking_select_public"
on public.ranking
for select
to anon
using (true);

create policy "ranking_insert_public"
on public.ranking
for insert
to anon
with check (
  char_length(nome) between 1 and 16
  and pontuacao >= 0
  and pontuacao <= 999999
);
